### ISSUE TITLE
[질문] 상품 테이블에 좋아요 카운팅 추가

### ISSUE THREAD

**Issue by mingdyuo** [BAECHOOs/Spring-toyproject#17]
좋아요 DB 구현을 찾아보다가 발견한 [게시글](http://yoonbumtae.com/?p=3287)에서 본 내용입니다.

> count를 사용하는 경우, 게시판 초기 로딩 시 카운트 수를 불러오기가 매우 어려워집니다. 일일히 게시글 수 만큼 count 작업을 수행해야 하며 단일 JOIN으로 처리하기도 어렵습니다.
> 만일 처리가 가능하더라도 반복된 SELECT 호출로 인해 성능 저하를 일으킬 수 있습니다.

그래서 product 테이블에 like_count 필드를 추가하고 좋아요/좋아요취소 시 값을 같이 변경해주는 것은 어떨까요??

**Comment by osj3474** [comment]
넵 전 좋아요~!

**Comment by HYEEWON** [comment]
어제 likes INT로 추가했는데 like_count로 변경할까요?

**Comment by osj3474** [comment]
ERDcloud에서 추가하신 거죠? 넵넵 like_count로 바꿔주시면 감사하겠습니당~!
