### ISSUE TITLE
[공부] Spring Security team (민주, 상진)

### ISSUE THREAD

**Issue by osj3474** [BAECHOOs/Spring-toyproject#8]
1) 유투브랑 블로그 예제 영상보면서 감을 익히기
2) UserDetailsService, PasswordEncoder, AuthenticationManager, ProviderManager, AuthenticationProvider 등에 대해서 알아보기
3) 위의 클래스들에 사용되는 Spring 어노테이션들, 메서드 정리하기

**Comment by osj3474** [comment]
https://spring.io/guides/gs/securing-web/

공식문서 입니다@!

**Comment by osj3474** [comment]
https://github.com/GentleDot/spring-security-demo

백기선님 강의 정리가 너무 잘 되어있네요!!! 같이 공부합시다~~!

**Comment by mingdyuo** [comment]
좋습니다!~!~!

**Comment by osj3474** [comment]
구현 완료되었습니다~!
